# Generated by Django 5.1.2 on 2024-11-09 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userspassword_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userspassword',
            name='username',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
