# Generated by Django 5.1.2 on 2024-11-11 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='file',
        ),
        migrations.AlterField(
            model_name='notification',
            name='content',
            field=models.CharField(blank=True, max_length=100000, null=True),
        ),
    ]
